### ISSUE TITLE
add optional data file name for startup

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#176]
For folks who run models for several cases, an option (like in pave) to include datafile name when firing the Verdi would be a great help saving many clicks.  For example
 verdi -f wrfout_d1.nc)

**Comment by lizadams** [comment]
This option to load files using the -f option does work.  However, if there are several files with the same name, but in different directories, VERDI does not know that it isn't the same, and will only load the file once.

I've run into this with students in the training class for CMAQ, where we are asking them to compare an MCIP file that they created with one in the answers directory using the following type of command:

verdi -f $cwd/METCRO2D_CMAS-Training.nc -f $ANSWERS/2_MCIP/METCRO2D_CMAS-Training.nc

This should load two files, but it only loads one.

Renaming one of the files to another name solves this issue, but it isn't ideal.
mv $ANSWERS/2_MCIP/METCRO2D_CMAS-Training.nc $ANSWERS/2_MCIP/METCRO2D_CMAS-Training.NEW.nc

VERDI will now load both files.  So - VERDI isn't keeping a record of the location where the file is loaded from, and is only loading by the filename, which is causing VERDI to think that it has already loaded a file, if it has the same name as a previously loaded file..

This will load two files, now that the second file has a new name:
verdi -f $cwd/METCRO2D_CMAS-Training.nc -f $ANSWERS/2_MCIP/METCRO2D_CMAS-Training.NEW.nc

**Comment by lizadams** [comment]
A student had the same issue:
After I typed the command 
"verdi –f $A_OUT/agts_l.*0707*ncf –f $ANSWERS/area/step_4/agts_l.*0707*ncf" ,
only the first dataset was loaded into VERDI. I don't know where I went wrong.
My recommendation was:
Alternatively, use the ls command to get the full path of the file names.  VERDI may be having trouble because of using the wildcards, it may think it is trying to load the same file twice.

The following works.

verdi -f /home/training/smoke/data/run_train_LNR/output/cmaq.cb05p25/agts_l.20060707.1.wus12.train_LNR.ncf -f /home/training/smoke/data/answers/area/step_4/agts_l.20060707.1.wus12.train.ncf

**Comment by lizadams** [comment]
This worked.  Tested using VERDI_2.0_beta_linux64_20190623.tar.gz
 ./verdi.sh -f $cwd/data/model/CCTM46_P16.baseO2a.36k.O3MAX -f $cwd/data/model/ans/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]-O3[2]" -g tile
<img width="1045" alt="Screen Shot 2019-06-24 at 3 14 54 PM" src="https://user-images.githubusercontent.com/1183863/60045422-d84fa280-9692-11e9-9458-0b0f6c8d916d.png">
