### ISSUE TITLE
Stats don't seem to work for MPAS

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#185]
•	Statistics (“Stats:”) plots do not seem to work for MPAS.

**Comment by lizadams** [comment]
[x] QA Testing for Stats: minimum value 
When I select this for the t2m variable in the t2m_only.nc file, I see the map change, and the lowest temperature values are depicted by the default color scheme as grey, and the temperature is located in the vicinity of Antarctica. The concern is that I have is that the values reported underneath the plot, for Min and Max seem to be reporting the correct lat/lon values, but not the correct temperatures.
The temperature value reported for the min, should match the lowest value on the color bar legend which is 201.673 K for the min, and 308.531 K for the max.
<img width="880" alt="t2m_stats_min" src="https://user-images.githubusercontent.com/1183863/49952841-c9f62200-feca-11e8-93b9-a4dbd94452c8.png">

**Comment by lizadams** [comment]
Note, the statistic: minimum is providing the minimum value of each grid cell over all of the timesteps.
So one grid cell in the domain is identified as having the minimum value among the minimum value of all of the grid cells, and  one grid cell is identified is having the maximum value among all of the minimum values over all of the grid cells.
If I change the plot min and max using configure plot to go from 305 K to 308.531K, and then zoom into the Middle East Region, I can probe the temperature value at the lat/lon that VERDI is reporting to have the maximum of the "minimum temperatures", and can confirm that this value matches the value at the top of the legend.
<img width="895" alt="t2m_maximum_value" src="https://user-images.githubusercontent.com/1183863/49954144-c748fc00-fecd-11e8-9385-186cbbe5163d.png">

**Comment by lizadams** [comment]
- [ ] QA check of the following Statistics for the t2m variable confirmed that the issue reported above for the incorrect value being reported under the plot for min and max values also occurs for other statistical measures.
- maximum
- mean

Timestep of minimum is working for the min and max values reported underneath the plot, but the probe value has the incorrect units (reporting K rather than #)
<img width="911" alt="timestep_of_minimum_t2m" src="https://user-images.githubusercontent.com/1183863/49954866-7cc87f00-fecf-11e8-966e-952a76333f77.png">

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1.3_linux64_20220210.tar.gz, found that Stats worked for MPAS file t2m_only.nc. The issue has resolved.**
![issue_185_testing_20220210_1](https://user-images.githubusercontent.com/73186639/155005880-78cb720a-931c-4479-8765-a8af5cbbfb53.png)
![issue_185_testing_20220210_2](https://user-images.githubusercontent.com/73186639/155005905-3cb7b966-9588-474c-856f-b3087fa63145.png)

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1.3_linux64_20220302.tar.gz (with updated JDK), found that Stats worked for MPAS file t2m_only.nc. But there were still some log messages showed up in the command window(shown as below).  Please remove them. 
![image](https://user-images.githubusercontent.com/73186639/156813551-dd507838-5524-48d0-b19f-ae0ba2ef4172.png)
![image](https://user-images.githubusercontent.com/73186639/156813783-6a981416-8a5d-4fbf-8156-73c8ed8be541.png)

**Comment by yadongxuEPA** [comment]
When I tried to retest this issue with VERDI_2.1.3_win64_20220302.zip on my PC, found **inconsistency** of the displayed variable value at the bottom-left of VERDI window **between Linux64 build and win64 build** (not sure if this is caused by the updated JDK). 
**with Linux 64 build, at time step 1 with maximum zoom-out domain:**
![issue_185_testing_20220302_from_Linux_1](https://user-images.githubusercontent.com/73186639/156830923-1bbc10da-1de2-4229-9fe5-993709e4b0ea.png)
**with win64 build, at time step 1 with maximum zoom-out domain:**
![Verdi_testing_issue_185_from_win64_1](https://user-images.githubusercontent.com/73186639/156831074-9be825a7-577b-4de6-b94d-6e2204f19444.png)
 **with Linux 64 build, at time step 11 and zoomed-in to North America:**
![issue_185_testing_20220302_from_Linux_3](https://user-images.githubusercontent.com/73186639/156831301-3a9441c2-467c-4f90-b610-a210d594f027.png)
 **with win64 build, at time step 11 and zoomed-in to North America:**
![Verdi_testing_issue_185_from_win64_4](https://user-images.githubusercontent.com/73186639/156831396-d5d5964e-09e5-4569-a5f4-29c964958bbb.png)
My questions are: 1) Is this value meant to be the averaged value for the displayed domain at the domain centroid?
                              2) Why the values are different between linux64 and win64 build?
Hi Liz,
Can you check what is the test results on mac?  Thanks!

**Comment by lizadams** [comment]
It looks like the value circled above in red (position and t2m temperature values in the lower left corner of the VERDI application) does not appear until a windowed region is selected using the cursor and rubber band method to zoom into NA.

If I restart VERDI and then zoom in using
Control > Set Longitude and Latitude Ranges

Longitude: -140 .. -39
Latitude: 3 .. 65

Then I don't see the values in the lower left corner.

If I use the rubber band method, then the value appears.
 
I used the cursor and compared the values in the lower left with the cursor values in the lower right of the plot, and it seems to be similar to the values when the cursor position is placed in the lower right corner.

<img width="1159" alt="Screen Shot 2022-03-14 at 5 17 20 PM" src="https://user-images.githubusercontent.com/1183863/158262868-d194d0e6-2142-4c89-aa39-058b43d37e64.png">

When using a rubber band method to zoom into North America, I think it would be difficult to get the same value.  I am not sure.

**Comment by cbroker1** [comment]
Using `VERDI_2.1.4_win64_20220526.zip` I attempted to replicate @yadongxuEPA two examples. There's differences. 

Example 1:
<img width="945" alt="image" src="https://user-images.githubusercontent.com/43118284/171677377-8a6af82b-0604-430a-aad2-da31257cc676.png">

Log from above actions
<img width="686" alt="image" src="https://user-images.githubusercontent.com/43118284/171677602-15e94c1c-48d4-429f-ad4c-fcd253491b44.png">

Visual Plot does not appear to display data properly

(rebooted VERDI)
#Example 2:
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/43118284/171678410-a9b661da-bc6a-4d28-841b-7d2c2a15055e.png">

Log from above actions
<img width="684" alt="image" src="https://user-images.githubusercontent.com/43118284/171678469-66f2e43e-ae1c-419e-8672-30a508f7d3b8.png">

Successfully replicated Example #2

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1.4_linux64_20220706.tar.gz on Atmos, found that this issue has resolved.**
![VERDI_testing_issue_185_1](https://user-images.githubusercontent.com/73186639/177852433-3040777b-2132-4994-abb1-b8476f2d82d6.png)
![VERDI_testing_issue_185_2](https://user-images.githubusercontent.com/73186639/177852461-7e5a9c61-a1eb-45e0-a463-0d825262e2e9.png)

**Comment by lizadams** [comment]
Retesting using VERDI_2.1.4_linux64_20220720.tar.gz

```
./verdi.sh -f $cwd/data/model/t2m_only.nc -s "t2m[1]" -g tile
```

Verified that this appears to be fixed. Min and max values under the plot agree with the min and max value in the legend.
The time step button for these statistics should likely be greyed out, as the statistics are for the entire timeframe and don't change with timestep.

<img width="1365" alt="Screen Shot 2022-07-20 at 12 54 38 PM" src="https://user-images.githubusercontent.com/1183863/180039927-39fe61e0-18ea-48d2-ba72-05af32dc4880.png">

**Comment by lizadams** [comment]
Also tested using VERDI_2.1.4_win64_20220720.zip
on IBM Thinkpad.
Confirmed this issue is fixed.
