### ISSUE TITLE
Legend labels became not editable for "Time Series Bar Plot" in VERDI 2.1

### ISSUE THREAD

**Issue by yadongxuEPA** [CEMPD/VERDI#228]
**Describe the bug**
the legend labels in "Time Series Bar Plot" of VERDI 2.1 (VERDI_2.0_linux64_20210222.tar.gz, VERDI_2.0_win64_20210222.tar.gz, VERDI_2.0_mac_20210222.tar.gz) could not respond to user's edits.

**To Reproduce**
1. Open VERDI-GUI
2. Add this dataset "CCTM46_P16.base02a.36k.O3MAX" and create a formula for "O3[1]"
3. Click on "Time Series Bar Plot" and see the legend label saying "Series 1" at the bottom
4. Click on "Configure" on the plot menu and go to "Configure Plot" >> "Labels">>"Legend"
5. Edit the label in the "Text" box as "Avg. Value (ppmV)" 
3. Click on "Apply"
4. Check the legend label again 

**Expected behavior**
The legend label is expected to be changed from "Series 1" to "Avg. Value (ppmV)"

**Screenshots**
![ch10_time_series_bar_plot_legend_bottom](https://user-images.githubusercontent.com/73186639/110016658-4ca96880-7cf3-11eb-9bc3-5c40f156a2c1.png)

**Comment by lizadams** [comment]
It is now possible to edit the Title, and have it display.
The following script works to create the bar plot with the title specified below:

./verdi.command -f $cwd/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -titleString "Layer 1 O3[1] NEW TITLE" -gtype bar

However, if you change the spinner bar for the layer, then the User Specified Title goes away.
I think this is because the LAYER number in the title is getting updated each time the spinner is changed.

Layer 1 O3[1]  NEW TITLE
When you change the Layer Spinner Bar by increasing to layer 2 then the "NEW TITLE" portion of the Title goes away and the title is updated to reflect that the data being displayed is Layer 2, and the default title is used.

Layer 2 O3[1] 

It is possible to change the subtitles, and have those be retained even after changing the layer spinner.

./verdi.command -f $cwd/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -titleString "Layer 1 O3[1] NEW TITLE" -subTitle1 "NEW SUBTITLE" -subTitle2 "NEW SUBTITLE2" -gtype bar

**Comment by yadongxuEPA** [comment]
> I am not sure what the Legend Label is referring to on the Bar Plot.
> I can modify the Domain Axis and Range Axis.
> When I change the Legend Label Text, it doesn't appear anywhere, but I am not sure that there is a Legend that can be modified on this bar chart. We don't have a legend.

Hi Liz,
There is a checkbox in front of "Show legend" within Configure >> Labels >> Legend. If it is unchecked, then the legend & legend label will not show up. In the latest build, the default legend label was changed from "series 1" to "time step", but it is still not editable by users. While in "Time series" plot, it was editable.
![Issue228_VERDI_retest_03272021](https://user-images.githubusercontent.com/73186639/113187832-4db4b380-9227-11eb-9838-a0d7afc92b7c.png)

**Comment by systemsgo** [comment]
> > I am not sure what the Legend Label is referring to on the Bar Plot.
> > I can modify the Domain Axis and Range Axis.
> > When I change the Legend Label Text, it doesn't appear anywhere, but I am not sure that there is a Legend that can be modified on this bar chart. We don't have a legend.
> 
> Hi Liz,
> There is a checkbox in front of "Show legend" within Configure >> Labels >> Legend. If it is unchecked, then the legend & legend label will not show up. In the latest build, the default legend label was changed from "series 1" to "time step", but it is still not editable by users. While in "Time series" plot, it was editable.
> ![Issue228_VERDI_retest_03272021](https://user-images.githubusercontent.com/73186639/113187832-4db4b380-9227-11eb-9838-a0d7afc92b7c.png)

That label is set by editing the Domain Axis label.  The latest build disables the Legend panel for Time Series Bar plots.

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.0_linux64_20210405.tar.gz, VERDI_2.0_win64_20210405.tar.gz.  The legend panel for Time Series Bar Plot is disabled to be changed.

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210906.tar.gz on Atmos. **The Time Series Bar Plot worked properly and the upgraded openJDK has not caused any problem in this issue.**
