### ISSUE TITLE
Tile plot in VERDI 2.1 did not respond to the textbox value changes when set "Stats" to "custom percentile" and "hours of non compliance"

### ISSUE THREAD

**Issue by yadongxuEPA** [CEMPD/VERDI#230]
**Describe the bug**
When used "custom percentile" and "hours of non compliance"  statistics in the "Tile Plot" for VERDI 2.1 ( VERDI_2.0_linux64_20210222.tar.gz,  VERDI_2.0_win64_20210222.tar.gz, VERDI_2.0_mac_20210222.tar.gz), the tile plots did not respond to the changes made in the textbox supposedly referring to different percentile/compliance threshold values 

**To Reproduce**
1. Go to VERDI-GUI
2. Add this dataset "CCTM46_P16.base02a.36k.O3MAX" and create a formula "O3[1]"
3. Click on "Tile Plot"
3. Scroll down in the drop down menu behind "Stats", click on "custom_percentile" with the value in the textbox set at "0.12"
4. Create another tile plot with the value in the textbox set at "0.35"
5. Look at the differences in plot created in step 3 and step 4
6. Create one more tile plot by click on " hours_of_non_compliance" with the value in the textbox set at "0.075"
7. Create another tile plot with the value in the textbox set at " 0.090"
8. Look at the differences in plot created in step 6 and step 7

**Expected behavior**
The tile plots are expected to respond to the changed user made in the textbox, supposedly referring to the "custom percentile" values or non-compliance threshold values.

**Screenshots**
![ch10_stats_custom_percentile_1](https://user-images.githubusercontent.com/73186639/110023509-4323fe80-7cfb-11eb-8bdf-d66f4784992e.png)
![ch10_stats_custom_percentile_2](https://user-images.githubusercontent.com/73186639/110023528-461eef00-7cfb-11eb-9b1a-f182159d10e3.png)
![ch10_stats_hours_of_non_compliance_1](https://user-images.githubusercontent.com/73186639/110023544-4a4b0c80-7cfb-11eb-81c9-cb2ba8b6a5b7.png)
![ch10_stats_hours_of_non_compliance_2](https://user-images.githubusercontent.com/73186639/110023560-4d45fd00-7cfb-11eb-8363-866d4e829546.png)

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.0_linux64_20210311.tar.gz, VERDI_2.0_win64_20210311.tar.gz. The issue is partially resolved, but some details need to be clarified.  
(1) When tested with the dataset "CCTM46_P16.base02a.36k.O3MAX", the popup window for user to enter the value of custom percentile did show up.  
![Screenshot_issue230_retest_03112021_8](https://user-images.githubusercontent.com/73186639/111211921-5bbad100-85a5-11eb-8c68-0248851f1138.png)
But the calculated values in the map were incorrect, as shown in the following map, the minimum value for 75 percentile was shown as -1.574 ppmV (the minimum value for O3MAX should be no less than 0).  Theoretically, the 75 percentile should produce the same as the third quartile as shown in the map at the bottom.
![Screenshot_issue230_retest_custom_percentile_75](https://user-images.githubusercontent.com/73186639/111212473-04693080-85a6-11eb-891e-148437aeb01c.png)
![Screenshot_issue230_retest_third_quartile](https://user-images.githubusercontent.com/73186639/111212484-07642100-85a6-11eb-8843-f84ce2105dde.png)
(2) When tested with the dataset " t2m_only.nc", the popup window for user to enter the value of custom percentile did not show up.
(3) The maps did respond to the value changes in the textbox for Stats "hours_of_non_compliance", but the color map legend should bring up hours interval as integers instead of decimal numbers.
![Screenshot_issue230_retest_03112021_7](https://user-images.githubusercontent.com/73186639/111213028-b99be880-85a6-11eb-8d38-e78cc658b115.png)
![Screenshot_issue230_retest_03112021_5](https://user-images.githubusercontent.com/73186639/111213220-eb14b400-85a6-11eb-9f1b-0787b64b3404.png)

**Comment by lizadams** [comment]
Retesting this - and it isn't working, mainly because the color legend has an incorrect value, so it is difficult to tell what the min/max and range is for the statistics chosen.

I am using the following command line option to load the file and create the tile plot, and then using the Stats pull-down menu to select the various statistics, the output is available below:

lizadams% ./verdi.command -f $cwd/data/model/CCTM47_aac_spr06.12k.CONC.2006113.O3.ncf -s "O3[1]" -g tile 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.geotools.resources.NIOUtilities (file:/Applications/VERDI_2.0/plugins/core/lib/geo-19/gt-metadata-19.1.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.geotools.resources.NIOUtilities
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021.03.31 12:06:30.700 [Thread-3] ERROR anl.verdi.plot.gui.FastTilePlot - FastTilePlot's run method
java.lang.ArithmeticException: / by zero
	at gov.epa.emvl.TilePlot.drawAxis(TilePlot.java:353) ~[core.jar:?]
	at gov.epa.emvl.TilePlot.draw(TilePlot.java:190) ~[core.jar:?]
	at anl.verdi.plot.gui.FastTilePlot$5.run(FastTilePlot.java:642) [core.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:832) [?:?]
Stat index 20 pre -1 item custom_percentile
Stat index 20 pre 20 item custom_percentile (10)
Stat index 20 pre -1 item custom_percentile
Stat index 20 pre 20 item custom_percentile (.45)
2021.03.31 12:08:06.887 [Thread-5] ERROR anl.verdi.plot.gui.FastTilePlot - FastTilePlot's run method
java.lang.ArithmeticException: / by zero
	at gov.epa.emvl.TilePlot.drawAxis(TilePlot.java:353) ~[core.jar:?]
	at gov.epa.emvl.TilePlot.draw(TilePlot.java:190) ~[core.jar:?]
	at anl.verdi.plot.gui.FastTilePlot$5.run(FastTilePlot.java:642) [core.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:832) [?:?]
Stat index 20 pre -1 item custom_percentile
Stat index 16 pre 20 item hours_of_non_compliance

Plot for Statistics: timestep of minimum:
<img width="908" alt="Screen Shot 2021-03-31 at 12 12 09 PM" src="https://user-images.githubusercontent.com/1183863/113176490-8b5f0f80-921a-11eb-8809-722196b8a2bd.png">

**Comment by lizadams** [comment]
Using the same dataset that Yadong used above and choosing the Statistic: Timestep of Minum
./verdi.command -f $cwd/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -g tile

<img width="899" alt="Screen Shot 2021-03-31 at 12 19 26 PM" src="https://user-images.githubusercontent.com/1183863/113177377-70d96600-921b-11eb-9858-b018775a386c.png">

**Comment by lizadams** [comment]
./verdi.command -f $cwd/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -g tile
Stastic: Hours of Non-compliance > .05
(Note, you need to widen
<img width="1068" alt="Screen Shot 2021-03-31 at 12 21 55 PM" src="https://user-images.githubusercontent.com/1183863/113177743-d9284780-921b-11eb-88bb-e368a8e8af58.png">
 the VERDI Plot window to see the text box, in order to enter a value.)

**Comment by yadongxuEPA** [comment]
Retested with the dataset " t2m_only.nc" on the new build "VERDI_2.0_linux64_20210327.tar.gz". Found that the popup window for user to enter the value of custom percentile did show up. However, as Liz mentioned above, the new issue of the color map legend occurred.   

![Issue230_VERDI_retest_03272021](https://user-images.githubusercontent.com/73186639/113181179-7c2e9080-921f-11eb-92ef-f6cbd7b07c4f.png)

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.0_linux64_20210405.tar.gz, VERDI_2.0_win64_20210405.tar.gz on two datasets. Found that the issue of  "custom_percentile"  was resolved . The 75 percentile did produce the same map as the third quartile.
![Issue_230_VERDI_testing_04052021_2N3](https://user-images.githubusercontent.com/73186639/114051672-4dd23600-985b-11eb-80d9-00c64b13153f.png)
![Issue_230_VERDI_testing_04052021_4N5](https://user-images.githubusercontent.com/73186639/114051689-5165bd00-985b-11eb-97f4-a7d9eac9b78f.png)
"hours_of_non_compliance" worked on "CCTM46_P16.base02a.36k.O3MAX". However, the Max value at the bottom was incorrect when tested on "t2m_only.nc" as shown in the bottom map.
![Issue_230_VERDI_testing_04052021_7](https://user-images.githubusercontent.com/73186639/114052634-32b3f600-985c-11eb-9d6d-fac71c9f47f6.png)
![Issue_230_VERDI_testing_04052021_6](https://user-images.githubusercontent.com/73186639/114052641-35aee680-985c-11eb-8b01-f71a64a40aed.png)

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.0_linux64_20210408.tar.gz, VERDI_2.0_win64_20210408.tar.gz on "t2m_only.nc".  The same issue of "hours_of_non_compliance" described above persisted.

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210526.tar.gz on two datasets, "CCTM46_P16.base02a.36k.O3MAX" and "t2m_only.nc".  Found that the issue has resolved.
![issue_230_VERDI_testing_20210526](https://user-images.githubusercontent.com/73186639/119864707-e9416800-bee8-11eb-9c74-f4f113c3e1cd.jpg)

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210906.tar.gz on two datasets, "CCTM46_P16.base02a.36k.O3MAX" and "t2m_only.nc". Found that the issue has resolved.
![issue_230_VERDI_testing_1_20210906](https://user-images.githubusercontent.com/73186639/132384537-870bdca8-77ac-40d2-bf5f-27c9963549b5.jpg)
![issue_230_VERDI_testing_3_20210906](https://user-images.githubusercontent.com/73186639/132384610-6f722e74-178d-49ae-81ae-f2641d682184.jpg)
![issue_230_VERDI_testing_4_20210906](https://user-images.githubusercontent.com/73186639/132384624-f4664fab-adaf-42f1-a2bf-e588db5bfaf4.jpg)
