### ISSUE TITLE
Areal interpolation color mapping incorrect

### ISSUE THREAD

**Issue by cwsimmon** [CEMPD/VERDI#250]
Reported by Russ Bullock

When doing an areal interpolation of 2-meter temperature data (../data/model/t2m_only.nc) using the HUC region 3 shape file (../data/hucRegion/huc03.shp), the colors shown in the resulting interpolation map do not match the interpolated values indicated by the probe.  The probe values appear to be correct.  The colors and/or contour values in the legend are not correct.  I tried the same areal interpolation using the 3-d water vapor mixing ratio data (variable qv) in the file (../data/model/history_qv_only.2016-07-04_00UTC.nc).  For all layers, the same problem existed.  The colors plotted do not match the realistic data values indicated by the probe.

Test file *t2m_only.2016-07-04.nc* can be found at /work/MOD3DEV/rbullock/Verdi

**Comment by yadongxuEPA** [comment]
**To Reproduce**
Steps to reproduce the behavior:

1) Load the 2-meter temperature data file "t2m_only.2016-07-04.nc" into verdi and create tile plot of  "t2m" variable.
    Zoom to the southeast part of the United States. 
2) Load the HUC region 3 shape file ((../data/hucRegion/huc03.shp) under "Area Files" and pick "HUC" field.
3) Click on "Areal Interp" tab to create an areal interpolation plot. 

**Expected behavior**
The interpolated values in these shapes are accurate  and displayed correctly in the map.

**Tested with VERDI_2.1_linux64_20210707.tar.gz and confirmed that the issue has not resolved.**  
![issue_250_VERDI_testing_1_and_2_07072021_editted](https://user-images.githubusercontent.com/73186639/125669536-c36ff189-e052-4f7f-99f3-4f3f195bbcfc.jpg)

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20210809.tar.gz and confirmed that the issue has not resolved.**
The color map legend was changed slightly from the ones generated from VERDI 20210707 build, but the interpolated values are displayed incorrectly.  
![issue_250_VERDI_testing_1_20210809](https://user-images.githubusercontent.com/73186639/128935085-c32bd588-90bc-4ae4-a5d0-171ddcf44281.jpg)

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20210906.tar.gz and confirmed that the issue has not resolved.**
The color map legend was changed slightly from the ones generated from the previous build, but the interpolated values were still displayed incorrectly.
![issue_250_VERDI_testing_1_20210906](https://user-images.githubusercontent.com/73186639/132554437-4c6d71eb-a206-46ab-b7ec-1f4a976ccfd4.jpg)

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210913.tar.gz and confirmed that the issue has not resolved.
The color map seemed being consistent with the tile plot, but the interpolated values displayed in the bottom bar was inconsistent with the color map legend. Using the HUC ID 3110201 as an example, the averaged t2m value was displayed as 254.8002K, but the color for that specific polygon was red (indicating it was in-between 271.051-309.773K).
![issue_250_VERDI_testing_20210913](https://user-images.githubusercontent.com/73186639/133297165-98919708-29f4-470a-a090-67d9315d5772.png)

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20210914.tar.gz and verified that the issue has resolved.**
![issue_250_VERDI_testing_2_20210914](https://user-images.githubusercontent.com/73186639/133473754-971985cf-c97e-416f-94c0-a50307cf6226.png)
