### ISSUE TITLE
severe message written to command window (not to log file)

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#54]
I think that the following 2 messages are printed to the command window when a tile plot is drawn. These messages are apparently from the GeoTools library because they are not written to the log file.

[current date& time] org.geotools.data.shapefile.files.ShpFiles logCurrentLockers
SEVERE: The following locker still has a lock: read on file:/C:/VERDI_test/VERDI_1.6.0_test04042016/plugins/bootstrap/data/map_county/tl_2015_us_county.shp by org.geotools.data.shapefile.shp.ShapefileReader

[current date& time] org.geotools.data.shapefile.files.ShpFiles logCurrentLockers
SEVERE: The following locker still has a lock: read on file:/C:/VERDI_test/VERDI_1.6.0_test04042016/plugins/bootstrap/data/map_county/tl_2015_us_county.shx by org.geotools.data.shapefile.shp.IndexFile

**Comment by cseppan** [comment]
Since the file tl_2015_us_county.shp is larger than 100 MB, it's stored using Git Large File Storage (https://git-lfs.github.com). This means that the full file isn't checkout out by default, just a small text file that looks like this:

```
version https://git-lfs.github.com/spec/v1
oid sha256:a647ffca45804c97c670c2c0c42c1402997774a2f8861516cb457d650b704a30
size 119006612
```
Since this isn't a valid shapefile, it won't get loaded in properly, and consequently doesn't get cleaned up properly, leading to the lock error messages.

To check out the full file, install the Git LFS extension, then use `git lfs pull` to download the file.

**Comment by joellenb** [comment]
Replaced shapefile for US counties with the 1:500,000 resolution cartographic US counties boundaries file from US Census Bureau (https://www.census.gov/geo/maps-data/data/cbf/cbf_counties.html) and changed the mapper.java file to read from this file.
