### ISSUE TITLE
number format - colormap

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#60]
Reported by Tony Howard, April 9, 2016
We found a couple of problems with how the Number Format is handled when
you configure a plot.  According to the docs I found at
https://www.cmascenter.org/verdi/documentation/1.5/VerdiUserManual1.5.htm#_Toc402110829,
the number format is supposed to follow the behavior of C's printf
format string, but it's not quite working.  Here's a summary of the
problems, and my recommendations on fixes:
1.  When I set the number format to %2.1f and click apply then ok, the
   map still shows values with 3 decimal places.  This is happening because
   ColorMap.setLogMinMax(double, double) sets this.format to null.  That
   gets rid of the format that was set in the configure dialog, and
   replaces it with the default 3 decimal place value.  I think the right
   solution is just to take out the this.format = null line.  That would
   avoid resetting to default whenever the min/max values change.
2.  After the first fix, when I set the number format to %9.3f and click
   apply then ok, the map still shows 615.682.  The first number in my
   format string specifies the formatted string should be at least 9
   characters wide, so I should see 00615.682.

This is happening because PalettePanel.resetNumberFormat(ColorMap,
String) parses the format string, converts it into a DecimalFormat
pattern string, and uses that to create a DecimalFormat to simulate the
printf behaviour.  That pattern string isn't quite correct, and due to
limitations in the DecimalFormat API, I'm not sure it can be entirely
fixed.  Even if it could, it would take a lot of code, and there's  a
much easier way to get the same result.  There's a static method on
String called format that takes a C style printf format string as the
first argument, and a value to format as the second argument.  You can
get the same result by replacing all references to
ColorMap.getNubmerFormat() with a new ColorMap.getFormatString() method
that returns the string entered in the configure dialog, and all code
that previously called ColorMap.getNumberFormat().format(value) with
String.format(ColorMap.getFormatString(), value).  There are probably a
bunch of places where that change would need to be made, but it's a
pretty simple change, and you'd get correct handling of the printf
string without needing to re-implement it.

**Comment by joellenb** [comment]
We will test these 2 formatting issues. However, please note that the information in point 2 is incorrect based on Kernighan and Ritchie (1978). The format for printf is defined in section 7.3. The paragraph concerning the digit string specifying a minimum field width says:

"The converted number will be printed in a field at least this wide, and wider if necessary. If the converted argument has fewer characters than the field width it will be padded on the left (or right, if the left adjustment indicator has been given) to make up the field width. The padding character is blank normally and zero if the field width was specified with a leading zero (this zero does not imply an octal field width)."

Please test the format string %09.3f with your chart and let us know if that gives you the leading zeros. Thanks!

**Comment by joellenb** [comment]
Full printf options are not available in VERDI. The VERDI documentation needs to reflect what are supported. 

The formatting has been reworked and is ready for testing. Here is how the user-supplied format should be working:

[leading non-digit][0][width].[decimals][E][0]

[leading non-digit]: optional; earlier had leading %; not required; any non-digit characters before the first digit is ignored
[0]: optional; if present values may be formatted to have leading 0’s to match the overall width
[width]: sum of [decimals] + 1 for . + desired number of places before the .; is recomputed in code if too small; note that width > decimals or width will be recomputed by VERDI
.: separator between the values for [width] and for [decimals]
[decimals]: number of decimal places requested
[E]: optional; if present display in scientific notation (e.g., 2.33E-2) otherwise display in regular float notation (e.g., 0.0233)
[0]: trailing zero AFTER the E is optional; the code puts on a trailing zero if one isn’t there

**Comment by systemsgo** [comment]
Printf formatting should work now - feel free to test with standard options.

**Comment by lizadams** [comment]
- [x] QA check for the number format
This is what is in the documentation:
Number Format: To specify the number format used in the map legend, 
enter the format [leading non-digit][0][width].[decimals][E][0] 
What I observed is that the width is ignored.  The decimal and E or F after the decimal works.
So, no additional zeros are added to pad the number if the width is specified to be wider than the number.
@systemsgo - I am not sure if it is necessary to have the ability to specify the width of the number.  If it isn't needed then we can go ahead and close this issue.
