### ISSUE TITLE
Coordinate Information for Shapefiles

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#70]
VERDI used to display the coordinate information for shapefiles when adding a plot for use in Areal Interpolation as shown in [Figure 8.4 ](https://www.cmascenter.org/verdi/documentation/1.5/VerdiUserManual1.5.htm#_Toc402111243) and projection information in [Figure 8.5](https://www.cmascenter.org/verdi/documentation/1.5/VerdiUserManual1.5.htm#_Toc402111244) in the VERDI User Manual.

**Comment by cseppan** [comment]
I think that's the behavior if the selected shapefile doesn't include a prj file.

**Comment by lizadams** [comment]
The huc03 file is what I used has a prj file. Perhaps it doesn't match the requirements that you mentioned in the Release Notes.
cat huc03.prj
GEOGCS["unnamed ellipse",DATUM["D_unknown",SPHEROID["Unknown",6371007,0],TOWGS84[0,0,0]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

From the Release Notes for VERDI 1.6.0 alpha
Shapefiles for areal interpolation must use units of degrees (not meters) and should use the following datum: DATUM[“unknown”, SPHEROID[“SPHERE”, 6370000.0, 0.0], TOWGS84[0,0,0]

**Comment by lizadams** [comment]
Do we have a way to obtain shapefiles that meets these requirements?

**Comment by systemsgo** [comment]
It only asks for the projection information when it can't determine the projection automatically from the prj file.  Since the huc03.prj file is correct, it picks it up automatically, and doesn't ask.  To simulate this behavior, move huc03.prj to a different directory before loading the .shp.  This happens in the code when ProjectionCard calls Target.loadProjectionInfo(), and it returns null.
