### ISSUE TITLE
Tile Plot new default color palette doesn't support more than 8 bins - for Default Tile Plot 

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#73]
I tried reproducing a plot that used 10 bins in the Legend for [Figure 12-4](https://www.cmascenter.org/verdi/documentation/1.5/VerdiUserManual1.5.htm#_Toc402111299) and noticed that the new default color palate doesn't allow you to go above 8.  You can put 10 in the Configure Plot> Color Map > Number of Tiles Textbox, but when you select Rebuild, only 8 tiles are used.
![screenshot_default_color_palette](https://cloud.githubusercontent.com/assets/1183863/14722014/7aca8ae6-07d7-11e6-93f8-3bc5fdb46e54.png)

**Comment by joellenb** [comment]
The default color palette is always 8 bins. Those are the original PAVE colors. If you want more or less than 8 bins, you must select a different color scheme.

Jo Ellen

**Comment by lizadams** [comment]
In VERDI 1.5.0 the user is able to specify the number of tiles to be used in the Map Range Color Palette in the Configure> Configure Plot > Color Map
There is a spin toggle to choose the number of tiles.  

In VERDI_2.0_beta, this doesn't work.  The number of tiles is fixed at 8, and if the user tries to load a config file with fewer number of tiles specified, then the color palette is BLANK, and other than the map, the plot has no titles, and 
<img width="533" alt="screen shot 2019-01-17 at 11 15 01 am" src="https://user-images.githubusercontent.com/1183863/51331492-dc262b80-1a47-11e9-989e-bc498a316275.png">
looks like it contains no data.
./verdi.sh -f /pine/scr/u/s/ushankar/analysis/output/FSJVA_base43st_10_12k/tileplots/CCTM_V502_Linux2_x86_64ifort_cb05tucl_ae6_aq.FSJVA_base43st_10_12k.combine_aconc_O3.204308.ncf -s "O3[1]" -configFile /nas/longleaf/home/lizadams/verdi_1.5_5bin_config -g tile

[verdi_1.5_5bin_config.txt](https://github.com/CEMPD/VERDI/files/2769486/verdi_1.5_5bin_config.txt)

**Comment by lizadams** [comment]
OK - if the user chooses another palette, then they can select the number of tiles in the palette.  I need to do more testing to determine what the problem was with the configuration file.

**Comment by jherwehe** [comment]
Working interactively with VERDI_2.0_beta.20190610, I was able to reproduce the problem of a blank plot without tiles when loading a plot configuration file that had been saved using VERDI v1.5.0.  To fix the problem, change the line

    <Format type="java.text.DecimalFormat" pattern="#0.000" />

in the VERDI v1.5.0 plot configuration file to

    <Format type="anl.verdi.plot.util.PrintfNumberFormat" pattern="-2.3f" />

to make the saved plot configuration file compatible with VERDI_2.0_beta.  This fix works for both CMAQ and WRF plot configuration files.

We probably should not worry about maintaining backward compatibility here; the newer line is better because its number format matches the Number Format shown to the user in the Configure -> Configure Plot -> Color Map dialogue box.  Users will need to update this line in any of their saved VERDI v1.5.0 plot configurations that they wish to use with newer versions of VERDI.
