### ISSUE TITLE
Time Series Plot uses Layer 1

### ISSUE THREAD

**Issue by joellenb** [CEMPD/VERDI#82]
From the Tile Plot, zoom in on a region, go to a Time Step and Layer.
![ftpzoomts22l3_05112016](https://cloud.githubusercontent.com/assets/10145737/15195708/0094f7d2-1797-11e6-862f-377b99881ffe.PNG)
Placed cursor on cell (123,49). Selected Plot/Time Series of Probed Cell(s). Shows as Layer 1.
![ftpzoomprobel3_05112016](https://cloud.githubusercontent.com/assets/10145737/15195905/f4ffe87c-1797-11e6-93cb-87ce1175e28f.PNG)
The curve does change when the Layer widget on the time series plot is changed to a different layer.

**Comment by lizadams** [comment]
[x] QA testing
When a user creates a tileplot, then changes the layer from 1 to  3, and then uses the Probe to select a grid cell, and then does Plot > Timeseries of Probed Cell 
The Timeseries plot that is created by default shows the timeseries of layer 1 rather than layer 3.   

The user can use the layer control on the timeseries plot to switch to layer 3 to see the timeseries plot for that layer.
[ ] Need to add a note to the documentation 
closing this issue
